### Numpy is a linear algebra library for python

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built In Methods

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Zeroes & Ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace

In [13]:
#returns evenly spaced numbers over a specified intervals

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

#### Eye

In [17]:
# Creates an identity matrix
#all elements are 0 except diagonal which is 1

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [19]:
np.random.rand(2)

array([0.18501795, 0.74799057])

In [20]:
np.random.rand(5,5)

array([[0.05180615, 0.86746118, 0.2464766 , 0.10946296, 0.60023881],
       [0.77248876, 0.55348785, 0.86206759, 0.38075136, 0.62796572],
       [0.7420076 , 0.50508831, 0.61493497, 0.0633342 , 0.95073153],
       [0.45734108, 0.19947479, 0.6618087 , 0.27937128, 0.54319658],
       [0.22609466, 0.07873522, 0.43505417, 0.61376289, 0.83362892]])

In [21]:
#normal distribution
np.random.randn(2)

array([ 0.79599602, -0.90975587])

In [22]:
np.random.randn(5,5)

array([[-0.20482432, -0.28418174,  0.57911691,  0.13898724, -0.88897978],
       [-0.50330526, -0.2607097 ,  0.62423042, -1.15562941,  1.37500271],
       [-1.31614366, -1.51281895,  0.55529519, -0.35113241,  0.2719366 ],
       [ 0.19044601,  0.94327682,  0.13852112, -1.17768025,  1.02169238],
       [ 0.9778157 , -1.44292601,  0.95997856,  0.86344684, -0.38978989]])

In [23]:
#random integer
np.random.randint(1,100)

97

In [24]:
np.random.randint(1,100,10)

array([20, 47, 14, 11, 16, 77, 96, 98,  3, 99])

In [27]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr=np.random.randint(0,50,10)
ranarr

array([18, 38, 28,  7, 35, 18, 20, 26, 24, 16])

### Reshape

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

In [31]:
ranarr

array([18, 38, 28,  7, 35, 18, 20, 26, 24, 16])

In [33]:
ranarr.max()

38

In [34]:
ranarr.min()

7

In [35]:
ranarr.argmax()

1

In [36]:
ranarr.argmin()

3

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.shape

(25,)

In [42]:
arr.reshape(25,1).shape

(25, 1)

In [43]:
arr.dtype

dtype('int32')

## Numpy Indexing and Selection

In [44]:
arr=np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection

In [47]:
arr[8] #value at index 8

8

In [48]:
#get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [50]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr=np.arange(0,10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
#creating slices of array
slice_of_arr= arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [56]:
#if you dont want changes to happen in original array then need to take copy
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [57]:
arr_copy[:]=50

In [59]:
print(arr_copy)
print(arr)

[50 50 50 50 50 50 50 50 50 50]
[99 99 99 99 99 99  6  7  8  9]


### Indexing a 2D array (matrices)

In [60]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[1][0]

20

In [63]:
#2d array slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

### Fancy Indexing

In [69]:
arr2d=np.zeros((10,10))

In [70]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr_length=arr2d.shape[1]

In [72]:
arr_length

10

### Selection

In [73]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr=arr>4

In [75]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])